// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Property.Infrastructure.EF.Contexts;

#nullable disable

namespace Property.Infrastructure.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20260421023320_InitialStructure")]
    partial class InitialStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.CiudadReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("itemId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("paisId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("paisId");

                    b.HasKey("Id");

                    b.HasIndex("paisId");

                    b.ToTable("ciudad");
                });

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.PaisReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("paisId");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("pais");
                });

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.PropiedadReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("propiedadItemId");

                    b.Property<Guid>("ciudadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ciudadId");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("direccion");

                    b.Property<bool>("fueVerificado")
                        .HasColumnType("bit")
                        .HasColumnName("fueVerificado");

                    b.Property<Guid>("tipoPropiedadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tipoPropiedadId");

                    b.HasKey("Id");

                    b.HasIndex("ciudadId");

                    b.HasIndex("tipoPropiedadId");

                    b.ToTable("propiedad");
                });

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.ServicioReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("servicioId");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("servicio");
                });

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.TipoPropiedadReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tipoPropiedadId");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("tipoPropiedad");
                });

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.CiudadReadModel", b =>
                {
                    b.HasOne("Property.Infrastructure.EF.ReadModel.PaisReadModel", "Pais")
                        .WithMany()
                        .HasForeignKey("paisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Property.Infrastructure.EF.ReadModel.PropiedadReadModel", b =>
                {
                    b.HasOne("Property.Infrastructure.EF.ReadModel.CiudadReadModel", "Ciudad")
                        .WithMany()
                        .HasForeignKey("ciudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Property.Infrastructure.EF.ReadModel.TipoPropiedadReadModel", "TipoPropiedad")
                        .WithMany()
                        .HasForeignKey("tipoPropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("TipoPropiedad");
                });
#pragma warning restore 612, 618
        }
    }
}
